### ISSUE TITLE
Make a point about delay between building and getting binaries from openSUSE repositories.

### ISSUE THREAD

**Issue by rominf** [openSUSE/obs-docu#1]
I'm a newbie. I  brought OBS best practice book from opensuse/doc and read: "And from there, click on Go to download repository. You'll see something like this..." (http://doc.opensuse.org/products/draft/OBS/obs-best-practices_draft/cha.obs.best-practices.webuiusage.html#id349510). I do precisely what's written and get error. That's confusing.

May be it should contain something like that (I'm not a native English speaker, so that phase is probably bad formed): "WARNING! Uploading binaries to our servers can take a while! So you need to wait several hours to see binaries in repositories! If you want to grab them immediately, you get them from there (point to links below "Go to download repository"):  ...".

**Comment by bgeuken** [comment]
Thanks for reporting this. We've added a short paragraph regarding the possible publishing delay: https://github.com/openSUSE/obs-docu/pull/20
