### ISSUE TITLE
Default daps example in README.md doesn't work

### ISSUE THREAD

**Issue by wengel** [openSUSE/obs-docu#139]
The default daps example in README.md results in error:

#> daps -d DC-obs-beginners-guide validate

ERROR: Wrong path for the DC-file
       (provided on the command line: DC-obs-beginners-guide)

The file DC-obs-beginners-guide doesn't exist anymore.
Some other files might be used instead, for example DC-obs-user-guide.

I'm creating a pull-request for that.

**Comment by wengel** [comment]
Created [pull-request](https://github.com/openSUSE/obs-docu/pull/140)

**Comment by tomschr** [comment]
Thanks, :+1:  this is now merged (commit 37150b4).
