### ISSUE TITLE
Additional note of the service type "disabled" is wrong

### ISSUE THREAD

**Issue by dcermak** [openSUSE/obs-docu#174]
The following part of the documentation says that the service type `disabled` exists since OBS 2.11:
https://github.com/openSUSE/obs-docu/blob/e8556bf78b6ab5c0f96db1ff6922232dfd63c76b/xml/obs_source_service.xml#L214

But the description further below says that `mode=disabled` existed before 2.11.

cc @adrianschroeter

**Comment by adrianschroeter** [comment]
On Mittwoch, 11. November 2020, 14:16:44 CET Dan Čermák wrote:
> The following part of the documentation says that the service type `disabled` exists since OBS 2.11:
> https://github.com/openSUSE/obs-docu/blob/e8556bf78b6ab5c0f96db1ff6922232dfd63c76b/xml/obs_source_service.xml#L214
> 
> But the description further below says that `mode=disabled` existed before 2.11.

fixed that in new pull request

-- 

Adrian Schroeter <adrian@suse.de>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH,  Maxfeldstr. 5, 90409 Nuernberg, Germany
(HRB 247165, AG München), Geschäftsführer: Felix Imendörffer

**Comment by JanZerebecki** [comment]
Fixed in https://github.com/openSUSE/obs-docu/pull/154 would close issue if I could.
