### ISSUE TITLE
Crop screenshots to remove browser bar

### ISSUE THREAD

**Issue by bgeuken** [openSUSE/obs-docu#18]
It's just eating up space and is distracting readers. And it's not relevant for the documentation.

**Comment by akshat5302** [comment]
I would like to contribute could you just elaborate the issue @bgeuken

**Comment by hennevogel** [comment]
@akshat5302 this was done already, sorry. If you are looking for something else to do for the OBS documentation pick another issue :)

**Comment by akshat5302** [comment]
It's ok @hennevogel
