### ISSUE TITLE
Add links to github

### ISSUE THREAD

**Issue by rominf** [openSUSE/obs-docu#2]
I didn't find links to github in this book. I think it could be placed there: http://doc.opensuse.org/products/draft/OBS/obs-best-practices_draft/appendix.work_on_obs_book.html

**Comment by bgeuken** [comment]
Thanks for the report.

This has been fixed meanwhile in a9f323a6d976cecbd112ff6f774a027cfb7092ae

The most current version of our documentation can be found here:
http://openbuildservice.org/help/manuals/obs-best-practices/appendix.work_on_obs_book.html
