### ISSUE TITLE
Remove/replace Google+ in the "Share this page" Documentation footer 

### ISSUE THREAD

**Issue by LenzGr** [openSUSE/obs-docu#226]
The footer of the OBS User Guide contains a "Share this page" feature that still provides to share the page via Google Plus, which has been discontinued in April 2019. I'd like to suggest removing that part, or replace it with alternative social networks (e.g. Pinterest, Instagram, etc.)

![Screenshot from 2022-03-23 10-49-37](https://user-images.githubusercontent.com/263427/159672068-19c1b140-a60f-4205-9c71-6d20c8f69841.png)

**Comment by hennevogel** [comment]
Ey Hamburger, this is a [daps](https://opensuse.github.io/daps/) theme, would need fixing there.

**Comment by tomschr** [comment]
Thanks @LenzGr and @hennevogel. This is already fixed long time ago. The reason for this is, that the OBS documentation still uses old stylesheets. You need to change this line

https://github.com/openSUSE/obs-docu/blob/b40d0cdcd0199b6458af1d47d2865ec97f85cd2f/DC-obs-admin-guide#L18

in all DC files and use:

```
STYLEROOT="/usr/share/xml/docbook/stylesheet/suse2022-ns"
```

**Comment by hennevogel** [comment]
ui ui ui. that's like 10 years forward ;-)

**Comment by LenzGr** [comment]
Thanks a lot!
