### ISSUE TITLE
which source services are available on the server?

### ISSUE THREAD

**Issue by JanZerebecki** [openSUSE/obs-docu#241]
Which source services are available on the server? Can an admin paste a list?

---

I want to document some expectations from source services, which are:
* Do not run untrusted code. E.g. not from the input (_service file), the net or the OBS project. (These things need isolation from anything outside the project, so also isolation from the net. So responsibilites are split here between two: Running untrusted code is done during the build phase, which provides isolation. OBS source services use network access.)
* Require cryptographic verification based on input in the _service file or the OBS project. For ease of automatic review it needs to fail closed, unless this is explicitly requested in the _service file.
* Provide reproducible results and a way to verify them. As source obtained via network can change, provide a way to address ones that are supposed to not change. Often these are full version identifiers as found in lock-files of language package managers or URLs with the full version that are supposed to remain stable. In some cases one goal is to pick the latest version, e.g. from git. This can still be done securely when checking that the history is not rewritten and a signature matches a keyring. To make it reproducible version identifiers can be stored in _servicedata and used during reproduction.

It would be useful to know which services fulfill these criteria. And check these in obs-service-source_validator which is run by osc during commit and a bot before Factory acceptance. The important services to look at are those used in Factory and those available on the server build.opensuse.org.

---

I don't know which source services are available on the server build.opensuse.org and it seems there is no way for a non-admin to find out.

While the manual tells us where we can find the sources services in the local file system and thus we can check which are available:
https://github.com/openSUSE/obs-docu/blob/5ce4affb690676d46d397cf9b60ebada09af9d02/xml/obs_source_service.xml#L120
It doesn't tell us how to find out which are available on the server.

There are Recommends for services in the spec file of OBS, maybe these should match:
https://github.com/openSUSE/open-build-service/blob/4deaf3bcc9d70dd9e7280384f34c1722b2c9f57e/dist/obs-server.spec#L234

The pattern devel_osc_build maybe should have some relation to this (it currently doesn't): https://build.opensuse.org/package/view_file/openSUSE:Tools/patterns-devel-osc/patterns-devel-osc.spec?expand=1

We probably need an API call for telling us which services are available, but until then we can document the state of build.opensuse.org and build.suse.de as a recommendation.

---

I know build.opensuse.org has at least:
 * tar_scm obs_scm tar snapcraft appimage gbp https://github.com/openSUSE/obs-service-tar_scm
 * recompress https://github.com/openSUSE/obs-service-recompress
 * extract_file https://github.com/openSUSE/obs-service-extract_file
 * set_version https://github.com/openSUSE/obs-service-set_version

Didn't check or know about:
 * source_validator https://github.com/openSUSE/obs-service-source_validator/
 * download_assets https://github.com/openSUSE/obs-service-download_assets
 * cargo_vendor https://github.com/openSUSE/obs-service-cargo_vendor
 * node_modules https://github.com/openSUSE/obs-service-node_modules
 * go_modules https://github.com/openSUSE/obs-service-go_modules
 * replace_using_package_version https://github.com/openSUSE/obs-service-replace_using_package_version
 * format_spec_file https://github.com/openSUSE/obs-service-format_spec_file
 * kiwi_import https://github.com/openSUSE/obs-service-kiwi_import
 * erlang_changes https://github.com/openSUSE/obs-service-erlang_changes
 * refresh_patches https://github.com/openSUSE/obs-service-refresh_patches
 * download_url https://github.com/openSUSE/obs-service-download_url
 * download_files https://github.com/openSUSE/obs-service-download_files
 * product_converter https://github.com/openSUSE/obs-service-product_converter
 * bundle_gems https://github.com/openSUSE/obs-service-bundle_gems
 * bazel_repositories https://github.com/openSUSE/obs-service-bazel_repositories
 * update_changelog https://github.com/openSUSE/obs-service-update_changelog
 * git_tarballs https://github.com/openSUSE/obs-service-git_tarballs
 * renderspec https://github.com/openSUSE/obs-service-renderspec
 * python_requires https://github.com/openSUSE/obs-service-python_requires
 * github_tarballs https://github.com/openSUSE/obs-service-github_tarballs
 * container_checks https://github.com/openSUSE/obs-service-container_checks
 * part2pkg https://github.com/openSUSE/obs-service-part2pkg
 * verify_file https://build.opensuse.org/package/show/openSUSE:Tools/obs-service-verify_file
 * rust2rpm https://pagure.io/fedora-rust/rust2rpm
 * replace_using_env https://build.opensuse.org/package/show/Virtualization/obs-service-replace_using_env
 * rearchive https://build.opensuse.org/package/show/openSUSE:Tools/obs-service-rearchive
 * kubevirt_containers_meta https://github.com/kubevirt/kubevirt
 * kiwi_metainfo_helper https://build.opensuse.org/package/show/openSUSE:Tools/obs-service-kiwi_metainfo_helper
 * kiwi_label_helper https://build.opensuse.org/package/show/openSUSE:Tools/obs-service-kiwi_label_helper
 * generator_pom https://build.opensuse.org/package/show/openSUSE:Tools/obs-service-generator_pom
 * generator_driver_update_disk https://build.opensuse.org/package/show/openSUSE:Tools/obs-service-generator_driver_update_disk
 * download_src_package https://build.opensuse.org/package/show/openSUSE:Tools/obs-service-download_src_package
 * docker_label_helper https://build.opensuse.org/package/show/openSUSE:Tools/obs-service-docker_label_helper
 * cpanspec https://build.opensuse.org/package/show/openSUSE:Tools/obs-service-cpanspec
 * cdi_containers_meta https://github.com/kubevirt/containerized-data-importer
 * regex_replace https://build.opensuse.org/package/show/openSUSE:Tools/obs-service-regex_replace
 * increment_buildrelease https://build.opensuse.org/package/show/isv:ownCloud:devel/obs-service-increment_buildrelease
 * git-archive https://github.com/b1-systems/open-build-service-tools/tree/master/obs-service-git-archive
 * kde https://build.opensuse.org/package/show/KDE:Unstable:Frameworks/obs-service-kde
 * xslt https://github.com/toabctl/obs-service-xslt
 * j2gen https://github.com/toabctl/obs-service-j2gen
 * flatpak_vendor https://build.opensuse.org/package/show/home:sp1rit:testing/obs-service-flatpak_vendor
 * gpg-offline https://build.opensuse.org/package/show/home:sbrabec/obs-service-gpg-offline
 * build-resalloc https://github.com/praiskup/resalloc/tree/main/obs-service-build-resalloc
 * check_upgrade https://github.com/pandom79/obs-service-check_upgrade
 * fedpkg https://build.opensuse.org/package/show/home:k0da:obs-service/obs-service-fedpkg
 * npm_pack_cmd https://build.opensuse.org/package/show/home:illuusio:nodejs-packages/obs-service-npm_pack_cmd
 * npm_node_modules_cmd https://build.opensuse.org/package/show/home:illuusio:nodejs-packages/obs-service-npm_node_modules_cmd
 * library_dependency_mapper https://build.opensuse.org/package/show/home:adrianSuSE:old_services/obs-service-library_dependency_mapper
 * repack https://github.com/byteduty/obs-service-repack
 * generator_qmake https://build.opensuse.org/package/view_file/home:adrianSuSE:old_services/obs-service-generator_qmake/obs-service-generator_qmake.spec?expand=1
 * arch_repos_builder https://build.opensuse.org/package/show/home:dcassany:Arch/obs-service-arch_repos_builder
 * listadd https://build.opensuse.org/package/show/home:coldoch/obs-service-listadd
 * bash_script https://build.opensuse.org/package/show/home:blgardner:openSUSE:Tools/obs-service-bash_script
 * create_changelog https://build.opensuse.org/package/show/home:arachnos/obs-service-create_changelog
 * update_source https://build.opensuse.org/package/show/home:adrianSuSE:old_services/obs-service-update_source
 * dsc2spec https://github.com/jblunck/obs-service-dsc2spec

One should not use these:
 * cargo_audit https://github.com/openSUSE/obs-service-cargo_audit
   * The service is not rerun when the information is updated. The result of a run can not be queried (you'd need to download each package and run audit against it). The result is not reproducible. There is no ignore setting, as we often need to fix some issue but can not yet fix others.
     * Instead use cargo audit during build in the check section in the spec or in another package that BuildDepends on the one you want to check, as all these are automatically rerun when the vulnerability information changes.
     * You can also run cargo audit in your time triggered upstream CI.
 * python_sdist https://github.com/openSUSE/obs-service-python_sdist
   * Explained in https://github.com/openSUSE/obs-service-python_sdist/issues/8
 * git_buildpackage github.com/ronan22/obs-service-git-buildpackage
   * Seems to be an ancestor of gbp, so use the one from tar_scm.
 * tar-git https://github.com/MeeGoIntegration/obs-service-tar-git
 * repo https://github.com/MeeGoIntegration/obs-service-repo
   * The above two seems to be similar enough, so use tar_scm

This list was generated by searching this org for service and searching on build.opensuse.org with osc search -s obs-service and zypper search obs-service in Tumbleweed on 2022-07-21.

**Comment by hennevogel** [comment]
` osc api /service`

**Comment by hennevogel** [comment]
Documenting this is in is our [backlog](https://trello.com/c/U0WMkhok) for the [OpenAPI docs](https://build.opensuse.org/apidocs-new/) now

**Comment by hennevogel** [comment]
It's also documented already in the OpenAPI docu -> https://build.opensuse.org/apidocs-new/#/General%20Information/get_service
