### ISSUE TITLE
[Bug] Dead link in beginners guide 

### ISSUE THREAD

**Issue by rakoenig** [openSUSE/obs-docu#260]
## Problem

Beginners guide [Creating a New Project](https://openbuildservice.org/help/manuals/obs-user-guide/art.obs.bg.html#sec.obsbg.uc.newprj) explains the RPM spec file and says 

> For the complete spec file, see https://build.opensuse.org/package/view_file/home:obsgeeko/my-first-obs-package/my-first-obs-package.spec

Unfortunately it looks like the home:obsgeeko also got "garbage collected" because there were not activities for a long time.

## Impact

An absolute beginner in packaging might get stuck here. The spec file listed in the tutorial is not suitable for the package sources that were downloaded from GitHub previously, some build receipes for cmake are missing and also the build dependency for gcc-c++. 

This leads to the situation, that a beginner wont't get an RPM package but confusing errors in his build attempts. 

## What is needed?

Either restore the home:obsgeeko/my-first-obs-package so that we don't end up in a 404 or use the real spec file for the example file listed in the tutorial. So then a beginner can copy it from there.

**Comment by hennevogel** [comment]
@adrianschroeter guess you autocleaned `home:obsgeeko`?

**Comment by hennevogel** [comment]
I clicked the restore button now...

**Comment by smithfarm** [comment]
The link works fine today, so I'm closing this as "fixed".
