### ISSUE TITLE
SCM CI says that gitea does not support scoped API tokens - but it does

### ISSUE THREAD

**Issue by dcermak** [openSUSE/obs-docu#298]
In https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.scm_ci_workflow_integration.html#sec.obs.obs_scm_ci_workflow_integration.setup.token_authentication.how_to_authenticate_obs_with_scm it is said that gitea does not support scoped API tokens. However that is no longer true as of gitea 1.19:
![image](https://github.com/openSUSE/obs-docu/assets/45594031/b8d64a4d-9fce-4e3f-b3c5-dfbe8ad43e30)

It would be nice if the documentation would be updated accordingly listing the required scopes.

**Comment by smithfarm** [comment]
What are the required scopes? I'm guessing only the `repo` scope is needed and the rest not?
