### ISSUE TITLE
caches downloaded packages should be under `/var/tmp/oscbuild-packagecache`

### ISSUE THREAD

**Issue by bishal7679** [openSUSE/obs-docu#299]
## Issue
caches downloaded packages shoudld be under `/var/tmp/oscbuild-packagecache` instead of `/var/tmp/osbuild-packagecache`

Page link :- https://openbuildservice.org/help/manuals/obs-user-guide/art.obs.bg#sec.obsbg.req

section :- **Hardware Requirements**

**Comment by eduardoj** [comment]
Fixed by: #300.
