### ISSUE TITLE
Cross reference improvement

### ISSUE THREAD

**Issue by rjschwei** [openSUSE/obs-docu#314]
# Issue Description
The `Source Management` chapter in the section about SBOM generation contains the following information:

"""
Please check the build config documentation for the sbom flag.
"""

But there is no chapter or section titled "build config" that the user can easily find from the "Contents" menu.

Expected Result
============
Make "build config documentation" a link to the appropriate section in the document or change the wording to match a chapter and section such that the user can easily navigate to the relevant information.

How to Reproduce
===============
1. Go to https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.source_management#id-1.5.10.6.5
2. Click on 'Generating SBOM (Software Bill Of Material) Data'
3. You will see the sentence referenced above.

**Comment by smithfarm** [comment]
@rjschwei I opened a PR - #316 - to fix this. Can you comment there/review it?

**Comment by smithfarm** [comment]
![image](https://github.com/openSUSE/obs-docu/assets/3974844/b0a0b20c-281e-4dcd-ad58-fa493b717544)
