### ISSUE TITLE
constraints: not clear what setting "hardware:jobs" really does/means

### ISSUE THREAD

**Issue by smithfarm** [openSUSE/obs-docu#325]
The build constraints chapter mentions a constraint qualifier called `hardware:jobs` and says it is used "to require a minimal number of pre-configured parallel jobs for the build". But it's not clear what this actually means or how it is implemented.

**Comment by adrianschroeter** [comment]
On Dienstag, 13. Februar 2024, 18:05:31 CET Nathan Cutler wrote:
> The build constraints chapter mentions a constraint qualifier called `hardware:jobs` and says it is used "to require a minimal number of pre-configured parallel jobs for the build". But it's not clear what this actually means or how it is implemented.

it is actually a miss-use as jobs are not really
a hardware capability. It is just how the work is configured.

Maybe we should not even document it anymore as it is only 
miss-used and can not be really considered to be a 
real requirement to be able to build a source.

Some people just use it to get a maybe faster worker.

-- 

Adrian Schroeter ***@***.***>
Build Infrastructure Project Manager

SUSE Software Solutions Germany GmbH, Frankenstraße 146, 90461 Nürnberg, Germany
(HRB 36809, AG Nürnberg) Geschäftsführer: Ivo Totev

**Comment by smithfarm** [comment]
OK. It sounded like it somehow affects the `-j` setting passed to `make`/`cmake` ?

**Comment by smithfarm** [comment]
But now I'm guessing it means something like this: "My build uses `-j 4` so I want a build worker that can run at least four parallel build processes."

**Comment by smithfarm** [comment]
For example, as a reader, I don't understand how `hardware:jobs 4` differs from `hardware:processors 4`.

**Comment by smithfarm** [comment]
I have attempted to fix this in #326.
