### ISSUE TITLE
Problems with suse2022-ns stylesheet

### ISSUE THREAD

**Issue by hennevogel** [openSUSE/obs-docu#360]
- the SUSE logo. this is a not a SUSE product or project.
- neither this web page nor the documentation is fully copyrighted by SUSE but a collective work under a license. The rendering suggests otherwise
- disable sharing link, I really don't want to point to facebook and friends

@tomschr @fsundermeyer you have and idea how to work around those?

**Comment by tomschr** [comment]
> The report an issue link is not working. HTML looks like
> 
> ```
> <div class="icons"><a target="_blank" class="icon-reportbug" title="Report an issue">&nbsp;</a></div>
> ```

Yes, that's correct. The final links are added by JavaScript. You probably have disabled JavaScript in your browser, haven't you?

I get the report bug link, see screenshot below. When I use the developer tools to inspect the page, the `<a>` tag looks like this for the first section "1.1. Planning":

```html
<a target="_blank" class="icon-reportbug" title="Report an issue" href="https://github.com/SUSE/obs-docu/issues/new?title=%5Bdoc%5D%20Issue%20in%20%22Planning%22&amp;amp;body=Planning%3A%0A%0Afile%3A%2F%2F%2Fhome%2Ftoms%2Frepos%2FGH%2Fopensuse%2Fobs-docu%2Fbuild%2Fobs-admin-guide%2Fhtml%2Fbook.obs-admin%2Fobs.cha.installation_and_configuration.html%23_planning">&nbsp;</a>
```


----

![Screenshot_20240704_174019](https://github.com/openSUSE/obs-docu/assets/1312925/7637defe-c405-4a91-b7c6-b4b85e95c0ae)

**Comment by tomschr** [comment]
In regards to your questions:

> the SUSE logo. this is a not a SUSE product or project.

You can customize the logo by using the parameter `daps.header.logo`. By default, it points to `static/images/logo.svg`. Theoretically you can point to a different file, but I'm not sure if daps copies it. Perhaps we could integrate in the stylesheets an openSUSE logo.

If you prefer, you can also deactivate the logo completely by setting the `generate.logo` option to `0`.

> disable sharing link, I really don't want to point to facebook and friends

No problem, set the parameter `generate.share.and.print` to `0`.

To set all these different XSLT parameters, add them in the `DC-*` files as follows:

```shell
XSLTPARAM="--param generate.logo 0"
XSLTPARAM+=" --param generate.share.and.print 0"
```

Although you can put all parameters in one line, I would advise against it. If you have a separate line for every parameter you can comment its purpose and--if needed--you can temporarily disable it. You only need to take care of the additional space after the first quote. :wink:

**Comment by hennevogel** [comment]
@tomschr 💚 your support! thank you so much
