### ISSUE TITLE
[doc] Issue in "Project Build Configuration"

### ISSUE THREAD

**Issue by hramrach** [openSUSE/obs-docu#372]
Project Build Configuration:

https://openbuildservice.org/help/manuals/obs-user-guide/cha-obs-concepts#id-1.2.10.3.4.4

The content of build configuration is not described at all.

**Comment by adrianschroeter** [comment]
point 4.2 is about that?

**Comment by hramrach** [comment]
Hyperlinks don't exist?

**Comment by smithfarm** [comment]
@hramrach If I understand correctly, you would like the text of "22.1.2 Project Build Configuration" in the "OBS Concepts" chapter - i.e. https://openbuildservice.org/help/manuals/obs-user-guide/cha-obs-concepts#id-1.2.10.3.4.4

to link to

https://openbuildservice.org/help/manuals/obs-user-guide/cha-obs-prjconfig

If so, that does seem like a reasonable suggestion.

**Comment by smithfarm** [comment]
Well, we could consider deleting the entire **OBS Concepts** chapter, but that would require more thought and preparation than just this one bug report.

**Comment by hramrach** [comment]
great, thanks.
