### ISSUE TITLE
[doc] Issue in "SKELETON OF A SPEC FILE"

### ISSUE THREAD

**Issue by Wabri** [openSUSE/obs-docu#385]
## 

SKELETON OF A SPEC FILE:

https://openbuildservice.org/help/manuals/obs-user-guide/art-obs-bg#ex-obsbg-uc-basicprj-skeletonspec

## Description

The copy to clipboard button for the first example of skeleton file is "broken", the strings copied is:

```
#
# spec file for package my-first-obs-package
#
# -- Copyright omitted --

Name:           my-first-obs-package 
Version:        0.1.0 1
Release:        0 1
License:        GPL-3.0 1
Group:          Documentation 1
Summary:        Frobnication Tool 1
Url:            https://github.com/obs-example/my-first-obs-package 1
Source:         my-first-obs-package-%{version}.tar.gz 1
BuildRequires:  gcc 
BuildRequires:  cmake 2
BuildRoot:      %{_tmppath}/%{name}-%{version}-build

%description 
This tool frobnicates the bar with the foo when choosing the baz.

%prep 
%setup -q -n %{name}-%{version}

%build 

%install 

%files 
%defattr(-,root,root,-)
%doc README LICENSE *.txt
%{_bindir}/*

%changelog
```

If you can see that there are the **1** & **2** number from the element **Version** to **BuildRequires**.

The only differences I found in the art-obs-beginners-guide.xml from those references are xref are used instead of co tag. I've tested to validate the art-obs-beginners-guide.xml by substitute xref with co and it results in an error as expected.

Are there any other tags that can be used to solve this?

**Comment by hennevogel** [comment]
@tomschr this sounds like a theme/daps problem?

**Comment by Wabri** [comment]
Thanks :pray: I've subscribe to the issue to get notified when is solved!
