### ISSUE TITLE
E-book manual: wrong format

### ISSUE THREAD

**Issue by gdetrez** [openSUSE/obs-docu#8]
The downloadable manual link, which is advertised as being an epub file, gives you a docbook xml instead:

``` sh
~ ❯❯❯ wget http://openbuildservice.org/files/manuals/obs-reference-guide.epub
~ ❯❯❯ file obs-reference-guide.epub
obs-reference-guide.epub: XML document text
```

**Comment by hennevogel** [comment]
We only have user and admin guide now and both links are correct...
