### ISSUE TITLE
Beginner's Guide SPEC file not working

### ISSUE THREAD

**Issue by honyczek** [openSUSE/obs-docu#98]
I'm trying to follow Beginner's Guide to build obs-example/my-first-obs-package. But I can't build it, because of error. I'm beginner with OBS, I've never worked with spec files. I guess I have wrong configuration in example-osc.spec file, because I used example skeleton from the Beginner's Guide. But below the example is: "For the complete spec file, see https://github.com/obs-example/my-first-obs-package", but the link is to package, not to the spec file. Would be possible to correct the link to full spec file?

**Comment by hennevogel** [comment]
Hey @honyczek there is a vibrant community of developers, admins and users that support each other in their usage of the OBS. They meet online in a the [OBS IRC chat](irc://irc.freenode.net/openSUSE-buildservice) or on the [OBS mailing list](http://lists.opensuse.org/archive/opensuse-buildservice/). Here you can ask questions if you have trouble understanding something, you can seek advice and mingle with other OBS community members.

**Comment by marcus-h** [comment]
On 2018-04-09 11:16:24 +0000, Henne Vogelsang wrote:
> Closed #98.
> 
Hmm IMHO the bug is still valid, because the guide refers to
a non-existing spec file (which is supposed to be part of the git
repo).

**Comment by honyczek** [comment]
Thanks @marcus-h for advice how to complete the .spec file. It helped. But as you wrote this issue is about not working url in the Beginner's Guide. May be there is not such repository to link it. Would be better to put it directly into the guide? Same as the (not working) example?
